// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2231.OnyxTronix2016.subsystems;

import org.usfirst.frc2231.OnyxTronix2016.Robot;
import org.usfirst.frc2231.OnyxTronix2016.RobotMap;
import org.usfirst.frc2231.OnyxTronix2016.StickButtons;
import org.usfirst.frc2231.OnyxTronix2016.commands.*;

import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Encoder.IndexingType;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Shooter extends Subsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController shooterLeftMotor = RobotMap.shooterShooterLeftMotor;
    private final Encoder shooterIndexedEncoder = RobotMap.shooterShooterIndexedEncoder;
    private final SpeedController shooterRightMotor = RobotMap.shooterShooterRightMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Joystick buttonStick = Robot.oi.buttonStick;
	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new SpinAtSpeed());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	
	boolean isFinished = true;
	public void spinWheels() {
		
		if (buttonStick.getRawButton(StickButtons.Buttons.A.getValue())) {
			shooterLeftMotor.set(-1);
			shooterRightMotor.set(1);
			isFinished = false;
		} else if (buttonStick.getRawButton(StickButtons.Buttons.B.getValue())) {	
			shooterLeftMotor.set(1);
			shooterRightMotor.set(-1);
			isFinished = false;
		} else if(!isFinished){
			shooterLeftMotor.set(0);
			shooterRightMotor.set(0);
			isFinished = true;
			
		}

	}

	public void spinWheelsAtSpeed(double speed) {
		double spinSpeed = -speed > 0.15 ? -speed : 0;
		shooterLeftMotor.set(-spinSpeed);
		shooterRightMotor.set(spinSpeed);

	}
}
