// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.OnyxTronix2016.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2231.OnyxTronix2016.Robot;
import org.usfirst.frc2231.OnyxTronix2016.StickButtons;

/**
 *
 */
public class AutoCollect extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutoCollect() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.collector);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
//    	if(!Robot.reloader.isCollected()){
    	boolean isNeededToCollect = Robot.oi.getbuttonStick().getRawButton(StickButtons.Buttons.A.getValue()) && !Robot.reloader.isCollected();
    	if(isNeededToCollect){
    		Robot.collector.roll(1);
    		Robot.reloader.load(1);
    	}else{
    		Robot.collector.roll(-1);
        	Robot.reloader.load(-1);
    	}
//    	}else{
//    		Robot.collector.roll(false);
//        	Robot.reloader.load(false);
//    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if(Robot.oi.getbuttonStick().getRawButton(StickButtons.Buttons.RB.getValue())){
    		return Robot.reloader.isCollected();
    	}
    	return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.collector.roll(0);
    	Robot.reloader.load(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	
    }
}
