// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.OnyxTronix2016.commands;

import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.image.NIVisionException;

import org.usfirst.frc2231.OnyxTronix2016.Robot;
import org.usfirst.frc2231.OnyxTronix2016.RobotMap;
import org.usfirst.frc2231.OnyxTronix2016.subsystems.Shooter;

/**
 *
 */
public class CenterByVision extends Command {

	public double currentAreaRatio;
	public double lastAreaRatio;
	final double ratioSensetivity = 0.8;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	double m_setpoint;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public CenterByVision(double setpoint) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
    	m_setpoint = setpoint;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	if(!Robot.vision.isProcessing()){
    		Robot.vision.startProcessing();
        	Thread t = new Thread(Robot.vision.new VisionPID());
        	t.start();
    	}
    	RobotMap.VisionLeftPIDController.enable();
    	RobotMap.VisionRightPIDController.enable();
    	Robot.vision.setPIDSourceType(PIDSourceType.kRate);
    	Robot.vision.setPIDSourceType(PIDSourceType.kRate);
    	RobotMap.VisionLeftPIDController.setSetpoint(m_setpoint);
    	RobotMap.VisionRightPIDController.setSetpoint(m_setpoint);
    	Robot.shooter.setReady(false);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
//    	try {
//    		if(!Robot.shooter.isReady){
//    			currentAreaRatio = Robot.vision.calculateAreaRatio(Robot.vision.getReport());
//    			if(currentAreaRatio >= ratioSensetivity && currentAreaRatio <= 1)
//    				Robot.shooter.setReady(true);    			
//    			if(currentAreaRatio > lastAreaRatio){
//    				Robot.driveTrain.driveByDirection(90);
//    			}
//    			Robot.driveTrain.driveByDirection(270);
//    			lastAreaRatio = currentAreaRatio;
//    		}
//		} catch (NIVisionException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return RobotMap.VisionLeftPIDController.onTarget() && RobotMap.VisionRightPIDController.onTarget();
    }

    // Called once after isFinished returns true
    protected void end() {
		Robot.vision.stopProcessing();
		RobotMap.VisionLeftPIDController.disable();
		RobotMap.VisionRightPIDController.disable();
		Robot.shooter.setReady(true);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
		Robot.vision.stopProcessing();
		RobotMap.VisionLeftPIDController.disable();
		RobotMap.VisionRightPIDController.disable();
    }
}
